[default.extend-words]
crate = "crate"
GitHub = "GitHub"
MCP = "MCP"
mdBook = "mdBook"
Zotero = "Zotero"
THES = "THES"
supersed = "supersed"

[files]
extend-exclude = [
    "target",
    "book",
    "dist",
]
